name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: app
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
  K8S_DEPLOYMENT_NAME: app
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set image tag
        id: set-tag
        run: echo "image_tag=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to docker.io
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.set-tag.outputs.image_tag }}

  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    if: github.repository == 'unknown'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: set image deployment/{{ env.K8S_DEPLOYMENT_NAME }} container-0=${{ env.DOCKER_USERNAME }}/{{ env.DOCKER_IMAGE_NAME }}:${{ needs.build-image.outputs.image_tag }}
